-- migrate:up
ALTER TYPE "EventType" ADD value 'SYSTEM_BANK_ADD';
ALTER TYPE "EventType" ADD value 'SYSTEM_BANK_UPDATE';
ALTER TYPE "EventType" ADD value 'SYSTEM_BANK_DELETE';

-- migrate:down
CREATE TYPE "EventType_new" AS ENUM(
	'LOGIN',
	'REGISTER',
	'PASSWORD_RESET_REQUEST',
	'PASSWORD_RESET_TOKEN_VERIFICATION',
	'PASSWORD_RESET',
	'AUTHENTICATION',
	'AUTHORIZATION',
	'PROFILE_UPDATE',
	'USERNAME_CHANGE',
	'PASSWORD_CHANGE',
	'BANK_ADD',
	'BANK_UPDATE',
	'BANK_DELETE',
	'CHANGE_USER_STATUS',
	'EMAIL_VERIFICATION',
	'ACTIVE',
	'TRANSFER_WALLET',
	'RESTORE_WALLET',
	'TRANSACTION',
	'FLAG'
);

ALTER TABLE "Event" ALTER COLUMN "type" TYPE "EventType_new" USING ("type"::TEXT::"EventType_new");

ALTER TYPE "EventType" RENAME TO "EventType_old";

ALTER TYPE "EventType_new" RENAME TO "EventType";

DROP TYPE "EventType_old";
