// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM "SessionToken"
WHERE
  "userId" = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, userid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionToken, userid)
	return err
}
